<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by javadoc (build 1.6.0_20) on Fri Feb 03 10:19:24 PST 2012 -->
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<TITLE>
PolicyService (IntelliSend Policy Service 0.1 API)
</TITLE>

<META NAME="date" CONTENT="2012-02-03">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../../../../stylesheet.css" TITLE="Style">

<SCRIPT type="text/javascript">
function windowTitle()
{
    if (location.href.indexOf('is-external=true') == -1) {
        parent.document.title="PolicyService (IntelliSend Policy Service 0.1 API)";
    }
}
</SCRIPT>
<NOSCRIPT>
</NOSCRIPT>

</HEAD>

<BODY BGCOLOR="white" onload="windowTitle();">
<HR>


<!-- ========= START OF TOP NAVBAR ======= -->
<A NAME="navbar_top"><!-- --></A>
<A HREF="#skip-navbar_top" title="Skip navigation links"></A>
<TABLE BORDER="0" WIDTH="100%" CELLPADDING="1" CELLSPACING="0" SUMMARY="">
<TR>
<TD COLSPAN=2 BGCOLOR="#EEEEFF" CLASS="NavBarCell1">
<A NAME="navbar_top_firstrow"><!-- --></A>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="3" SUMMARY="">
  <TR ALIGN="center" VALIGN="top">
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../overview-summary.html"><FONT CLASS="NavBarFont1"><B>Overview</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-summary.html"><FONT CLASS="NavBarFont1"><B>Package</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#FFFFFF" CLASS="NavBarCell1Rev"> &nbsp;<FONT CLASS="NavBarFont1Rev"><B>Class</B></FONT>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="class-use/PolicyService.html"><FONT CLASS="NavBarFont1"><B>Use</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-tree.html"><FONT CLASS="NavBarFont1"><B>Tree</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../deprecated-list.html"><FONT CLASS="NavBarFont1"><B>Deprecated</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../index-all.html"><FONT CLASS="NavBarFont1"><B>Index</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../help-doc.html"><FONT CLASS="NavBarFont1"><B>Help</B></FONT></A>&nbsp;</TD>
  </TR>
</TABLE>
</TD>
<TD ALIGN="right" VALIGN="top" ROWSPAN=3><EM>
</EM>
</TD>
</TR>

<TR>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
&nbsp;<A HREF="../../../../edu/isi/policy/service/AbstractPolicySession.html" title="class in edu.isi.policy.service"><B>PREV CLASS</B></A>&nbsp;
&nbsp;<A HREF="../../../../edu/isi/policy/service/PolicyServiceFactory.html" title="class in edu.isi.policy.service"><B>NEXT CLASS</B></A></FONT></TD>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
  <A HREF="../../../../index.html?edu/isi/policy/service/PolicyService.html" target="_top"><B>FRAMES</B></A>  &nbsp;
&nbsp;<A HREF="PolicyService.html" target="_top"><B>NO FRAMES</B></A>  &nbsp;
&nbsp;<SCRIPT type="text/javascript">
  <!--
  if(window==top) {
    document.writeln('<A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>');
  }
  //-->
</SCRIPT>
<NOSCRIPT>
  <A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>
</NOSCRIPT>


</FONT></TD>
</TR>
<TR>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
  SUMMARY:&nbsp;NESTED&nbsp;|&nbsp;FIELD&nbsp;|&nbsp;CONSTR&nbsp;|&nbsp;<A HREF="#method_summary">METHOD</A></FONT></TD>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
DETAIL:&nbsp;FIELD&nbsp;|&nbsp;CONSTR&nbsp;|&nbsp;<A HREF="#method_detail">METHOD</A></FONT></TD>
</TR>
</TABLE>
<A NAME="skip-navbar_top"></A>
<!-- ========= END OF TOP NAVBAR ========= -->

<HR>
<!-- ======== START OF CLASS DATA ======== -->
<H2>
<FONT SIZE="-1">
edu.isi.policy.service</FONT>
<BR>
Interface PolicyService</H2>
<DL>
<DT><B>All Known Implementing Classes:</B> <DD><A HREF="../../../../edu/isi/policy/service/PolicyServiceImpl.html" title="class in edu.isi.policy.service">PolicyServiceImpl</A></DD>
</DL>
<HR>
<DL>
<DT><PRE>public interface <B>PolicyService</B></DL>
</PRE>

<P>
Service that manages transfer advice based on VO-level policies
<P>

<P>
<DL>
<DT><B>Author:</B></DT>
  <DD>David Smith</DD>
</DL>
<HR>

<P>

<!-- ========== METHOD SUMMARY =========== -->

<A NAME="method_summary"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>Method Summary</B></FONT></TH>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#addCleanup(edu.isi.policy.entity.Cleanup)">addCleanup</A></B>(<A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A>&nbsp;cleanup)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adds a new cleanup request to memory</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#addCleanups(edu.isi.policy.util.CleanupList)">addCleanups</A></B>(<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A>&nbsp;cleanups)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adds a list of cleanup requests to memory.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#addTransfer(edu.isi.policy.entity.Transfer)">addTransfer</A></B>(<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A>&nbsp;transfer)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Places a new transfer in the policy knowledge session</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#addTransfers(edu.isi.policy.util.TransferList)">addTransfers</A></B>(<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A>&nbsp;transfers)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Places new transfers in the policy knowledge session</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#getCleanups()">getCleanups</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/service/PolicySession.html" title="interface in edu.isi.policy.service">PolicySession</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#getPolicySession()">getPolicySession</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;java.util.List&lt;<A HREF="../../../../edu/isi/policy/entity/Resource.html" title="class in edu.isi.policy.entity">Resource</A>&gt;</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#getResources()">getResources</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#getTransfer(java.lang.String)">getTransfer</A></B>(java.lang.String&nbsp;transferId)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#getTransfers()">getTransfers</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#removeCleanup(java.lang.String)">removeCleanup</A></B>(java.lang.String&nbsp;id)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Removes a cleanup from memory</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#removeTransfer(java.lang.String)">removeTransfer</A></B>(java.lang.String&nbsp;transferId)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Removes a transfer from the knowledge session.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#setPolicySession(edu.isi.policy.service.PolicySession)">setPolicySession</A></B>(<A HREF="../../../../edu/isi/policy/service/PolicySession.html" title="interface in edu.isi.policy.service">PolicySession</A>&nbsp;policySession)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sets the policy session</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#updateCleanup(java.lang.String, edu.isi.policy.entity.Cleanup)">updateCleanup</A></B>(java.lang.String&nbsp;cleanupId,
              <A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A>&nbsp;newCleanup)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updates an existing cleanup in the policy service</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#updateCleanups(edu.isi.policy.util.CleanupList)">updateCleanups</A></B>(<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A>&nbsp;cleanups)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updates a list of cleanups in the policy service.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#updateTransfer(java.lang.String, edu.isi.policy.entity.Transfer)">updateTransfer</A></B>(java.lang.String&nbsp;transferId,
               <A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A>&nbsp;newTransfer)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updates the properties on a previously created transfer</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../edu/isi/policy/service/PolicyService.html#updateTransfers(edu.isi.policy.util.TransferList)">updateTransfers</A></B>(<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A>&nbsp;transfers)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updates a list of transfers in the policy service.</TD>
</TR>
</TABLE>
&nbsp;
<P>

<!-- ============ METHOD DETAIL ========== -->

<A NAME="method_detail"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="1"><FONT SIZE="+2">
<B>Method Detail</B></FONT></TH>
</TR>
</TABLE>

<A NAME="addTransfers(edu.isi.policy.util.TransferList)"><!-- --></A><H3>
addTransfers</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A> <B>addTransfers</B>(<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A>&nbsp;transfers)</PRE>
<DL>
<DD>Places new transfers in the policy knowledge session
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>transfers</CODE> - the new transfers to get advice from
<DT><B>Returns:</B><DD>the transfers that the requester should invoke, including any
         necessary URL or properties changes</DL>
</DD>
</DL>
<HR>

<A NAME="addTransfer(edu.isi.policy.entity.Transfer)"><!-- --></A><H3>
addTransfer</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A> <B>addTransfer</B>(<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A>&nbsp;transfer)</PRE>
<DL>
<DD>Places a new transfer in the policy knowledge session
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>transfer</CODE> - the transfer to add
<DT><B>Returns:</B><DD>the updated transfer from the knowledge session, or nothing if
         the transfer was not placed in memory</DL>
</DD>
</DL>
<HR>

<A NAME="removeTransfer(java.lang.String)"><!-- --></A><H3>
removeTransfer</H3>
<PRE>
void <B>removeTransfer</B>(java.lang.String&nbsp;transferId)</PRE>
<DL>
<DD>Removes a transfer from the knowledge session.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>transferId</CODE> - the ID of the transfer to remove</DL>
</DD>
</DL>
<HR>

<A NAME="getTransfers()"><!-- --></A><H3>
getTransfers</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A> <B>getTransfers</B>()</PRE>
<DL>
<DD><DL>

<DT><B>Returns:</B><DD>the transfers that are currently known in the knowledge session.</DL>
</DD>
</DL>
<HR>

<A NAME="getTransfer(java.lang.String)"><!-- --></A><H3>
getTransfer</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A> <B>getTransfer</B>(java.lang.String&nbsp;transferId)</PRE>
<DL>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>transferId</CODE> - ID of an existing transfer
<DT><B>Returns:</B><DD>the current version of the specified transfer</DL>
</DD>
</DL>
<HR>

<A NAME="updateTransfer(java.lang.String, edu.isi.policy.entity.Transfer)"><!-- --></A><H3>
updateTransfer</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A> <B>updateTransfer</B>(java.lang.String&nbsp;transferId,
                        <A HREF="../../../../edu/isi/policy/entity/Transfer.html" title="class in edu.isi.policy.entity">Transfer</A>&nbsp;newTransfer)</PRE>
<DL>
<DD>Updates the properties on a previously created transfer
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>transferId</CODE> - the ID of the transfer to update.
<DT><B>Returns:</B><DD>returns the new transfer object resulting from the policy rules
         running over the new properties</DL>
</DD>
</DL>
<HR>

<A NAME="getPolicySession()"><!-- --></A><H3>
getPolicySession</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/service/PolicySession.html" title="interface in edu.isi.policy.service">PolicySession</A> <B>getPolicySession</B>()</PRE>
<DL>
<DD><DL>

<DT><B>Returns:</B><DD>a new or existing policy session</DL>
</DD>
</DL>
<HR>

<A NAME="setPolicySession(edu.isi.policy.service.PolicySession)"><!-- --></A><H3>
setPolicySession</H3>
<PRE>
void <B>setPolicySession</B>(<A HREF="../../../../edu/isi/policy/service/PolicySession.html" title="interface in edu.isi.policy.service">PolicySession</A>&nbsp;policySession)</PRE>
<DL>
<DD>Sets the policy session
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>policySession</CODE> - the policy session</DL>
</DD>
</DL>
<HR>

<A NAME="getResources()"><!-- --></A><H3>
getResources</H3>
<PRE>
java.util.List&lt;<A HREF="../../../../edu/isi/policy/entity/Resource.html" title="class in edu.isi.policy.entity">Resource</A>&gt; <B>getResources</B>()</PRE>
<DL>
<DD><DL>

<DT><B>Returns:</B><DD>the list of known resources in memory</DL>
</DD>
</DL>
<HR>

<A NAME="addCleanup(edu.isi.policy.entity.Cleanup)"><!-- --></A><H3>
addCleanup</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A> <B>addCleanup</B>(<A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A>&nbsp;cleanup)</PRE>
<DL>
<DD>Adds a new cleanup request to memory
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>cleanup</CODE> - </DL>
</DD>
</DL>
<HR>

<A NAME="removeCleanup(java.lang.String)"><!-- --></A><H3>
removeCleanup</H3>
<PRE>
void <B>removeCleanup</B>(java.lang.String&nbsp;id)</PRE>
<DL>
<DD>Removes a cleanup from memory
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>id</CODE> - the ID of the cleanup</DL>
</DD>
</DL>
<HR>

<A NAME="getCleanups()"><!-- --></A><H3>
getCleanups</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A> <B>getCleanups</B>()</PRE>
<DL>
<DD><DL>

<DT><B>Returns:</B><DD>a list of all cleanups in the system</DL>
</DD>
</DL>
<HR>

<A NAME="addCleanups(edu.isi.policy.util.CleanupList)"><!-- --></A><H3>
addCleanups</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A> <B>addCleanups</B>(<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A>&nbsp;cleanups)</PRE>
<DL>
<DD>Adds a list of cleanup requests to memory.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>cleanups</CODE> - the list of cleanups
<DT><B>Returns:</B><DD>the resource cleanups that the client should invoke</DL>
</DD>
</DL>
<HR>

<A NAME="updateCleanup(java.lang.String, edu.isi.policy.entity.Cleanup)"><!-- --></A><H3>
updateCleanup</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A> <B>updateCleanup</B>(java.lang.String&nbsp;cleanupId,
                      <A HREF="../../../../edu/isi/policy/entity/Cleanup.html" title="class in edu.isi.policy.entity">Cleanup</A>&nbsp;newCleanup)</PRE>
<DL>
<DD>Updates an existing cleanup in the policy service
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>cleanupId</CODE> - ID of the cleanup<DD><CODE>newCleanup</CODE> - the new cleanup to update with
<DT><B>Returns:</B><DD>the modified cleanup</DL>
</DD>
</DL>
<HR>

<A NAME="updateTransfers(edu.isi.policy.util.TransferList)"><!-- --></A><H3>
updateTransfers</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A> <B>updateTransfers</B>(<A HREF="../../../../edu/isi/policy/util/TransferList.html" title="class in edu.isi.policy.util">TransferList</A>&nbsp;transfers)</PRE>
<DL>
<DD>Updates a list of transfers in the policy service.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>transfers</CODE> - the transfers to update
<DT><B>Returns:</B><DD>the updated transfers</DL>
</DD>
</DL>
<HR>

<A NAME="updateCleanups(edu.isi.policy.util.CleanupList)"><!-- --></A><H3>
updateCleanups</H3>
<PRE>
<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A> <B>updateCleanups</B>(<A HREF="../../../../edu/isi/policy/util/CleanupList.html" title="class in edu.isi.policy.util">CleanupList</A>&nbsp;cleanups)</PRE>
<DL>
<DD>Updates a list of cleanups in the policy service.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>cleanups</CODE> - the cleanups to update
<DT><B>Returns:</B><DD>the updated cleanups</DL>
</DD>
</DL>
<!-- ========= END OF CLASS DATA ========= -->
<HR>


<!-- ======= START OF BOTTOM NAVBAR ====== -->
<A NAME="navbar_bottom"><!-- --></A>
<A HREF="#skip-navbar_bottom" title="Skip navigation links"></A>
<TABLE BORDER="0" WIDTH="100%" CELLPADDING="1" CELLSPACING="0" SUMMARY="">
<TR>
<TD COLSPAN=2 BGCOLOR="#EEEEFF" CLASS="NavBarCell1">
<A NAME="navbar_bottom_firstrow"><!-- --></A>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="3" SUMMARY="">
  <TR ALIGN="center" VALIGN="top">
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../overview-summary.html"><FONT CLASS="NavBarFont1"><B>Overview</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-summary.html"><FONT CLASS="NavBarFont1"><B>Package</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#FFFFFF" CLASS="NavBarCell1Rev"> &nbsp;<FONT CLASS="NavBarFont1Rev"><B>Class</B></FONT>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="class-use/PolicyService.html"><FONT CLASS="NavBarFont1"><B>Use</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-tree.html"><FONT CLASS="NavBarFont1"><B>Tree</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../deprecated-list.html"><FONT CLASS="NavBarFont1"><B>Deprecated</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../index-all.html"><FONT CLASS="NavBarFont1"><B>Index</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../help-doc.html"><FONT CLASS="NavBarFont1"><B>Help</B></FONT></A>&nbsp;</TD>
  </TR>
</TABLE>
</TD>
<TD ALIGN="right" VALIGN="top" ROWSPAN=3><EM>
</EM>
</TD>
</TR>

<TR>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
&nbsp;<A HREF="../../../../edu/isi/policy/service/AbstractPolicySession.html" title="class in edu.isi.policy.service"><B>PREV CLASS</B></A>&nbsp;
&nbsp;<A HREF="../../../../edu/isi/policy/service/PolicyServiceFactory.html" title="class in edu.isi.policy.service"><B>NEXT CLASS</B></A></FONT></TD>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
  <A HREF="../../../../index.html?edu/isi/policy/service/PolicyService.html" target="_top"><B>FRAMES</B></A>  &nbsp;
&nbsp;<A HREF="PolicyService.html" target="_top"><B>NO FRAMES</B></A>  &nbsp;
&nbsp;<SCRIPT type="text/javascript">
  <!--
  if(window==top) {
    document.writeln('<A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>');
  }
  //-->
</SCRIPT>
<NOSCRIPT>
  <A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>
</NOSCRIPT>


</FONT></TD>
</TR>
<TR>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
  SUMMARY:&nbsp;NESTED&nbsp;|&nbsp;FIELD&nbsp;|&nbsp;CONSTR&nbsp;|&nbsp;<A HREF="#method_summary">METHOD</A></FONT></TD>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
DETAIL:&nbsp;FIELD&nbsp;|&nbsp;CONSTR&nbsp;|&nbsp;<A HREF="#method_detail">METHOD</A></FONT></TD>
</TR>
</TABLE>
<A NAME="skip-navbar_bottom"></A>
<!-- ======== END OF BOTTOM NAVBAR ======= -->

<HR>
Copyright &#169; 2012. All Rights Reserved.
</BODY>
</HTML>
